{
 "title": "Atlassian Status Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Prometheus to Exporter Responding",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "UP" }
   ],
   "targets": [
    {
     "expr": "up{job=\"atlassian_status_exporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Exporter to Status Endpoint Responding",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "UP" }
   ],
   "targets": [
    { "expr": "atlassian_status_scrape_url_up", "legendFormat": "{{url}}" }
   ]
  },
  {
   "title": "Status Page State",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "atlassian_status_state", "legendFormat": "{{url}} - {{description}}" }
   ]
  },
  {
   "title": "Service Collect Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "atlassian_status_collect_duration_seconds",
     "legendFormat": "{{url}}"
    }
   ]
  }
 ]
}